#pragma once

#include "desc/include.hpp"
#include "prop/include.hpp"
#include "w/include.hpp"

#include "controls.hpp"
#include "dock.hpp"
#include "drag_drop.hpp"
#include "edit_session.hpp"
#include "errors.hpp"
#include "id_scope.hpp"
#include "instance_guard.hpp"
#include "instance_stack.hpp"
#include "item_result.hpp"
#include "label_registry.hpp"
#include "nav.hpp"
#include "os_window.hpp"
#include "popup.hpp"
#include "resource_loader.hpp"
#include "simple_scopes.hpp"
#include "texture.hpp"
#include "tick.hpp"
#include "types.hpp"
#include "util.hpp"
#include "wrapper.hpp"
